name: Build Next.js Project

on:
  push:
    branches: [main]

jobs:
  build:
    uses: nirajan-devops/ci-workflows/.github/workflows/node.yml@main
    with:
      build-command: next build
      working-directory: .
