name: Deploy Next.js via Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nextjs-app .

      - name: Save Docker image to tar
        run: docker save nextjs-app > app.tar

      - name: Copy image to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar"
          target: "/home/${{ secrets.USERNAME }}/app.tar"

      - name: Install Docker and deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker $USER
              newgrp docker || true
            else
              echo "Docker is already installed"
            fi

            # Load and run the container
            docker load < app.tar
            docker stop nextjs-app || true && docker rm nextjs-app || true
            docker run -d -p 3000:3000 --name nextjs-app nextjs-app
