name: Deploy Next.js via Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nextjs-app .

      - name: Save Docker image to tar
        run: docker save nextjs-app -o app.tar

      - name: Copy image to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app.tar"
          target: "/home/${{ secrets.USERNAME }}/app.tar"
          strip_components: false
          tar_tmp_path: ""
          overwrite: true

      - name: Install Docker and deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if needed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi
            cd /home/${{ secrets.USERNAME }}

            echo "Checking that app.tar exists:"
            ls -lh app.tar
            
            # Load the Docker image (explicit file path)
            sudo docker load -i app.tar

            # Stop and remove existing container (if any)
            sudo docker stop nextjs-app || true
            sudo docker rm nextjs-app || true

            # Run the new container
            sudo docker run -d -p 3000:3000 --name nextjs-app nextjs-app


